FROM ubuntu:25.04

RUN apt update && apt install postgresql-client-17 awscli \ 
    nano telnet apt-transport-https ca-certificates curl \
    gnupg-agent software-properties-common openvpn unzip sshpass openssh-client less -y